Added support for Alpine.js
kitajs/html pull request #128
Opened 2024-02-18 10:27 UTC by B-R-P

Added alpine attributes similar to [htmx.d.ts](https://github.com/kitajs/html/blob/master/htmx.d.ts).

2024-02-19 18:01 UTC, arthurfiorette commented
Hey @B-R-P thanks for your work! Would you mind documenting it inside the README.md file?

2024-02-19 18:04 UTC, arthurfiorette requested changes

2024-02-19 18:04 UTC, arthurfiorette commented on alpine.d.ts
> +    'x-model'?: string;
```suggestion
```

remove duplicated field

2024-02-19 18:04 UTC, arthurfiorette commented on alpine.d.ts
> +declare namespace JSX {
```suggestion
// This file is a result from https://alpinejs.dev/
// Missing something? Please submit a issue report or a PR:
// https://github.com/kitajs/html

declare namespace JSX {
```

2024-02-20 15:35 UTC, B-R-P commented on alpine.d.ts
> +    'x-model'?: string;
Removed in 7d56ab7

2024-02-20 15:40 UTC, arthurfiorette approved these changes

2024-02-20 15:48 UTC, B-R-P commented
> Would you mind documenting it inside the README.md file?

Done in f3f2e03

2024-02-20 17:27 UTC, arthurfiorette commented
thanks!

2024-02-20 17:27 UTC, merged