Add missing select types and refactor
kitajs/html pull request #191
Opened 2024-04-18 14:16 UTC by JacopoPatroclo

This PR aims to fix [this](https://github.com/kitajs/html/issues/177) issue

First I've added the missing properties to the select jsx element typescript definition. I've added `autocomplete` and I've noticed that other properties were declared by the FormEvents interface so I've extended the select definition with that interface to avoid duplication.

Second I've removed all the duplicated `undefined`. In this case, they should be equivalent to `?:`. Let me know @arthurfiorette if you see any issue with this and if I'm missing something.

Third I've added another test file that will be used in the future to check that all the types that this library provides are consistent with what is expected.

What still needs to be done:
- [ ] Write more tests related to the types
- [ ] Generate changelog (?)

2024-04-18 14:44 UTC, arthurfiorette commented
> Second I've removed all the duplicated undefined. In this case, they should be equivalent to ?:. Let me know @arthurfiorette if you see any issue with this and if I'm missing something.

Using `?` and `undefined |` is required. Depending on the user's `exactOptionalPropertyTypes` configuration, it may force the user to define all properties as `<div prop={undefined} />`. 

In kita's tsconfig this is indeed duplicated, but we cannot ensure all users follow our tsconfig.

2024-04-18 14:45 UTC, arthurfiorette requested changes

2024-04-18 14:45 UTC, arthurfiorette commented on packages/html/jsx.d.ts
> -    accesskey?: undefined | string;
please add `undefined |` again.

2024-04-18 14:50 UTC, arthurfiorette commented
To generate a changelog, run `pnpm changeset` in the project's root.

https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md

2024-04-18 14:53 UTC, arthurfiorette commented
> Write more tests related to the types

We have two paths to follow here:

1. We find a complete test spec somewhere and copy/paste it here.
2. We wait for type issues to come and only merge them if they also add their tests here.

Adding more type tests without a issues we will probably end up with incorrect tests.

2024-04-18 15:29 UTC, JacopoPatroclo commented
> > Write more tests related to the types
> 
> We have two paths to follow here:
> 
> 1. We find a complete test spec somewhere and copy/paste it here.
> 2. We wait for type issues to come and only merge them if they also add their tests here.
> 
> Adding more type tests without issues we will probably end up with incorrect tests.

That's a valid point. I'll invest a little bit of time looking for a standard spec that we could use.
If I can't find anything that fits; we should grow that particular test suite organically as you suggested (2)

2024-05-01 09:19 UTC, JacopoPatroclo commented
@arthurfiorette I couldn't find any "standard" jsx definition for dom elements rendered on the server. There is a heavy focus (obviously) on client-side specific type definitions that are not good for the context of this library. We should roll our type definitions for now.

Ex. The onselect property is often defined as a function and not a string.

2024-05-01 21:01 UTC, arthurfiorette approved these changes

2024-05-02 11:44 UTC, arthurfiorette commented
Awesome! As always, thanks for your work @JacopoPatroclo! Is this ready to merge?

2024-05-02 11:47 UTC, JacopoPatroclo commented
> Awesome! As always, thanks for your work @JacopoPatroclo! Is this ready to merge?

I think so, maybe a squash merge is necessary to "hide" some "wrong" commits.

2024-05-02 11:57 UTC, merged